language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sandbox' ]; then cd .. && eval "mv $currentfolder generator-sandbox" && cd generator-sandbox; fi

